//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 03:36:22 PM BST 
//


package odin.shared.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the odin.shared.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: odin.shared.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response.Appendix.Info.Policies.Trust }
     * 
     */
    public Response.Appendix.Info.Policies.Trust createResponseAppendixInfoPoliciesTrust() {
        return new Response.Appendix.Info.Policies.Trust();
    }

    /**
     * Create an instance of {@link MimeTypes }
     * 
     */
    public MimeTypes createMimeTypes() {
        return new MimeTypes();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document.Metadata }
     * 
     */
    public odin.shared.xml.Document.Metadata createDocumentMetadata() {
        return new odin.shared.xml.Document.Metadata();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document.Metadata.Attributes }
     * 
     */
    public odin.shared.xml.Document.Metadata.Attributes createDocumentMetadataAttributes() {
        return new odin.shared.xml.Document.Metadata.Attributes();
    }

    /**
     * Create an instance of {@link Results.Document.Attributes.Attribute }
     * 
     */
    public Results.Document.Attributes.Attribute createResultsDocumentAttributesAttribute() {
        return new Results.Document.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link Results.Document }
     * 
     */
    public Results.Document createResultsDocument() {
        return new Results.Document();
    }

    /**
     * Create an instance of {@link Basic.Document.Words }
     * 
     */
    public Basic.Document.Words createBasicDocumentWords() {
        return new Basic.Document.Words();
    }

    /**
     * Create an instance of {@link Results.Document.Locale }
     * 
     */
    public Results.Document.Locale createResultsDocumentLocale() {
        return new Results.Document.Locale();
    }

    /**
     * Create an instance of {@link Response.Appendix.Info.Policies.Xml }
     * 
     */
    public Response.Appendix.Info.Policies.Xml createResponseAppendixInfoPoliciesXml() {
        return new Response.Appendix.Info.Policies.Xml();
    }

    /**
     * Create an instance of {@link Results.Document.Author }
     * 
     */
    public Results.Document.Author createResultsDocumentAuthor() {
        return new Results.Document.Author();
    }

    /**
     * Create an instance of {@link Search.Document }
     * 
     */
    public Search.Document createSearchDocument() {
        return new Search.Document();
    }

    /**
     * Create an instance of {@link Basic.Document }
     * 
     */
    public Basic.Document createBasicDocument() {
        return new Basic.Document();
    }

    /**
     * Create an instance of {@link Response.Appendix.Info }
     * 
     */
    public Response.Appendix.Info createResponseAppendixInfo() {
        return new Response.Appendix.Info();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Search.Document.Locale }
     * 
     */
    public Search.Document.Locale createSearchDocumentLocale() {
        return new Search.Document.Locale();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document.Metadata.Keywords }
     * 
     */
    public odin.shared.xml.Document.Metadata.Keywords createDocumentMetadataKeywords() {
        return new odin.shared.xml.Document.Metadata.Keywords();
    }

    /**
     * Create an instance of {@link MimeTypes.Document }
     * 
     */
    public MimeTypes.Document createMimeTypesDocument() {
        return new MimeTypes.Document();
    }

    /**
     * Create an instance of {@link Basic }
     * 
     */
    public Basic createBasic() {
        return new Basic();
    }

    /**
     * Create an instance of {@link Response.Appendix.Trust.Alternatives }
     * 
     */
    public Response.Appendix.Trust.Alternatives createResponseAppendixTrustAlternatives() {
        return new Response.Appendix.Trust.Alternatives();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document }
     * 
     */
    public odin.shared.xml.Document createDocument() {
        return new odin.shared.xml.Document();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document.Metadata.Author }
     * 
     */
    public odin.shared.xml.Document.Metadata.Author createDocumentMetadataAuthor() {
        return new odin.shared.xml.Document.Metadata.Author();
    }

    /**
     * Create an instance of {@link Response.Appendix.Info.Policies }
     * 
     */
    public Response.Appendix.Info.Policies createResponseAppendixInfoPolicies() {
        return new Response.Appendix.Info.Policies();
    }

    /**
     * Create an instance of {@link Results.Document.Attributes }
     * 
     */
    public Results.Document.Attributes createResultsDocumentAttributes() {
        return new Results.Document.Attributes();
    }

    /**
     * Create an instance of {@link Response.Appendix.Info.Subjects }
     * 
     */
    public Response.Appendix.Info.Subjects createResponseAppendixInfoSubjects() {
        return new Response.Appendix.Info.Subjects();
    }

    /**
     * Create an instance of {@link Search.Document.Keywords }
     * 
     */
    public Search.Document.Keywords createSearchDocumentKeywords() {
        return new Search.Document.Keywords();
    }

    /**
     * Create an instance of {@link Response.Appendix.Info.Policies.Zip }
     * 
     */
    public Response.Appendix.Info.Policies.Zip createResponseAppendixInfoPoliciesZip() {
        return new Response.Appendix.Info.Policies.Zip();
    }

    /**
     * Create an instance of {@link Response.Status }
     * 
     */
    public Response.Status createResponseStatus() {
        return new Response.Status();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document.Metadata.Attributes.Attribute }
     * 
     */
    public odin.shared.xml.Document.Metadata.Attributes.Attribute createDocumentMetadataAttributesAttribute() {
        return new odin.shared.xml.Document.Metadata.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link Response.Appendix.Trust }
     * 
     */
    public Response.Appendix.Trust createResponseAppendixTrust() {
        return new Response.Appendix.Trust();
    }

    /**
     * Create an instance of {@link Results.Document.Keywords }
     * 
     */
    public Results.Document.Keywords createResultsDocumentKeywords() {
        return new Results.Document.Keywords();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Search.Document.Added }
     * 
     */
    public Search.Document.Added createSearchDocumentAdded() {
        return new Search.Document.Added();
    }

    /**
     * Create an instance of {@link Search.Document.Attributes.Attribute }
     * 
     */
    public Search.Document.Attributes.Attribute createSearchDocumentAttributesAttribute() {
        return new Search.Document.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link Search.Document.Attributes }
     * 
     */
    public Search.Document.Attributes createSearchDocumentAttributes() {
        return new Search.Document.Attributes();
    }

    /**
     * Create an instance of {@link odin.shared.xml.Document.Metadata.Locale }
     * 
     */
    public odin.shared.xml.Document.Metadata.Locale createDocumentMetadataLocale() {
        return new odin.shared.xml.Document.Metadata.Locale();
    }

    /**
     * Create an instance of {@link Search.Document.Author }
     * 
     */
    public Search.Document.Author createSearchDocumentAuthor() {
        return new Search.Document.Author();
    }

    /**
     * Create an instance of {@link Response.Appendix }
     * 
     */
    public Response.Appendix createResponseAppendix() {
        return new Response.Appendix();
    }

}
