
package odin.odin.ws.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SleipnirService", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SleipnirService {


    /**
     * 
     * @param parameters
     * @return
     *     returns odin.odin.ws.jaxws.SearchResponse
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SearchResponse search(
        @WebParam(name = "search", targetNamespace = "http://sites.google.com/site/printmiles/Odin", partName = "parameters")
        Object parameters);

    /**
     * 
     * @param arg0
     * @return
     *     returns odin.odin.ws.jaxws.GetDocumentResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetDocumentResponse")
    public odin.odin.ws.jaxws.GetDocumentResponse.Return getDocument(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns odin.odin.ws.jaxws.UploadResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "upload", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.UploadResponse")
    public odin.odin.ws.jaxws.UploadResponse.Return upload(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        odin.odin.ws.jaxws.Upload.Arg0 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns odin.odin.ws.jaxws.BasicSearchResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "basicSearch", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.BasicSearch")
    @ResponseWrapper(localName = "basicSearchResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.BasicSearchResponse")
    public odin.odin.ws.jaxws.BasicSearchResponse.Return basicSearch(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        odin.odin.ws.jaxws.BasicSearch.Arg0 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns odin.odin.ws.jaxws.GetDocumentMetadataResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "getDocumentMetadata", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetDocumentMetadata")
    @ResponseWrapper(localName = "getDocumentMetadataResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetDocumentMetadataResponse")
    public odin.odin.ws.jaxws.GetDocumentMetadataResponse.Return getDocumentMetadata(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns odin.odin.ws.jaxws.GetServerInfoResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "getServerInfo", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetServerInfo")
    @ResponseWrapper(localName = "getServerInfoResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetServerInfoResponse")
    public odin.odin.ws.jaxws.GetServerInfoResponse.Return getServerInfo(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "getZipPolicy", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetZipPolicy")
    @ResponseWrapper(localName = "getZipPolicyResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetZipPolicyResponse")
    public int getZipPolicy(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "getXmlPolicy", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetXmlPolicy")
    @ResponseWrapper(localName = "getXmlPolicyResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetXmlPolicyResponse")
    public int getXmlPolicy(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://sites.google.com/site/printmiles/Odin")
    @RequestWrapper(localName = "getBarcodeUrl", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetBarcodeUrl")
    @ResponseWrapper(localName = "getBarcodeUrlResponse", targetNamespace = "http://sites.google.com/site/printmiles/Odin", className = "odin.odin.ws.jaxws.GetBarcodeUrlResponse")
    public String getBarcodeUrl(
        @WebParam(name = "arg0", targetNamespace = "http://sites.google.com/site/printmiles/Odin")
        String arg0);

}
