
package odin.odin.ws.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SleipnirServiceImplService", targetNamespace = "http://ws.odin.odin/", wsdlLocation = "http://192.168.1.64/Sleipnir?wsdl")
public class SleipnirServiceImplService
    extends Service
{

    private final static URL SLEIPNIRSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(odin.odin.ws.jaxws.SleipnirServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = odin.odin.ws.jaxws.SleipnirServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.1.64/Sleipnir?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.64/Sleipnir?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SLEIPNIRSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SleipnirServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SleipnirServiceImplService() {
        super(SLEIPNIRSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.odin.odin/", "SleipnirServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns SleipnirService
     */
    @WebEndpoint(name = "SleipnirServiceImplPort")
    public SleipnirService getSleipnirServiceImplPort() {
        return super.getPort(new QName("http://ws.odin.odin/", "SleipnirServiceImplPort"), SleipnirService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SleipnirService
     */
    @WebEndpoint(name = "SleipnirServiceImplPort")
    public SleipnirService getSleipnirServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.odin.odin/", "SleipnirServiceImplPort"), SleipnirService.class, features);
    }

}
